### PR TITLE
First RUN 

### PR DESCRIPTION
**Pull request by fadsel**

### CODE REVIEW

**Comment by UltiGeek** [comment]
for some reason i cant pull

**Comment by fadsel** [comment]
you dont need to , its already merged :walking:

**Comment by UltiGeek** [comment]
oohh ok let me try to view changes then

**Comment by UltiGeek** [comment]
sync fail

this is what i mean ?... i think i have commited the xml file and i cant undo it

**Comment by UltiGeek** [comment]
can't countinue , i fear will collapse

**Comment by fadsel** [comment]
click the cogs button :100:  undo recent commit 
as

**Comment by fadsel** [comment]
try this if it fails

ssss

**Comment by fadsel** [comment]
you have to commit before you try to sync :walking:

**Comment by UltiGeek** [comment]
confilcts
i have commit already but then i have xml file conflicting #howdoIfixConflicts

**Comment by UltiGeek** [comment]
how do i merge? git merge?

**Comment by UltiGeek** [comment]
kkk
i have merged no good results

**Comment by fadsel** [comment]
discard changes to the XML file , then pull ... i have included the net gitignore that will ignore the .idea files :walking:

**Comment by UltiGeek** [comment]
how do i discard changes

**Comment by fadsel** [comment]
right -click inside GUI over the file you need to discard :+1:

**Comment by UltiGeek** [comment]
done but new problems
fhdb

**Comment by fadsel** [comment]
did you make any changes , you can always delete your local repo and start fresh by cloning it from github :+1:

**Comment by UltiGeek** [comment]
hahahaaaa

**Comment by fadsel** [comment]
or you can copy your changes , then do  a fresh clone :100:

**Pull request merged**
